-- SYSTEM 后期可加入许可证功能
CREATE TABLE SYSTEM_INFO {
  ID TEXT NOT NULL,
  COMPANYNAME TEXT,
  VER TEXT,
  ABOUT TEXT
};
-- 联系电话18972101425
-- SYSTEM
INSERT INTO SYSTEM_INFO VALUES ('SYSTEM','租房管理系统','1.0.1','联系电话18972101425');
-- SELECT COMPANYNAME,VER,ABOUT FROM SYSTEM_INFO
-- 用户
CREATE TABLE STAFF(

  ORGID,
  STAFFCODE,
  PASSWORD,
  NAME,
  SEX,
  BIRTH,
  AGE,
  ADDRISS,
  PHONE

)