package com.ks.hrms.dao;

/**
 * 自动生成主键编号
 */
public interface AutoGenerateDocNo {

    /**
     * 根据类型生成主键
     * @param docType
     * 类型
     *
     * @return
     */
    String getDocNo(String docType);
}
